<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net8.0</TargetFramework><EnableDefaultCompileItems>false</EnableDefaultCompileItems></PropertyGroup>
  <ItemGroup>
    <Compile Include="../../Assets/Scripts/Idas3WheelFeedback.cs" />
    <Compile Include="../../Assets/Scripts/Idas3WheelFeedbackChecks.cs" />
    <Compile Include="Platform.cs" />
  </ItemGroup>
</Project>
